service: example-for-blog

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1
  environment: ${file(./.env.yml):}

functions:
  homepage:
    handler: handlers/homepage.handler
    events:
      - http:
          path: hello
          method: get
  users-create:
    handler: handlers/users/create.handler
    events:
      - http:
          path: users
          method: post
